### ISSUE TITLE
启动IDA Pro时无法加载插件

### ISSUE THREAD

**Issue by wu-yafeng** [Antelcat/ida_copilot#5]
C:\Users\**\Desktop\IDA Pro 8.3\plugins\ida_copilot.py: DLL load failed while importing sip: 找不到指定的模块。
Traceback (most recent call last):
  File "C:\Users\**\Desktop\IDA Pro 8.3\python\3\ida_idaapi.py", line 577, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Users/**/Desktop/IDA Pro 8.3/plugins/ida_copilot.py", line 5, in <module>
    from ida_copilot import panel
  File "C:\Users/**/Desktop/IDA Pro 8.3/plugins\ida_copilot\panel.py", line 4, in <module>
    from PyQt5 import QtWidgets
ImportError: DLL load failed while importing sip: 找不到指定的模块。

**Comment by wu-yafeng** [comment]
我最终的解决办法是:
1. 卸载电脑安装的python
2. 在IDA的python目录中，如`python311` 中打开powershell
3. 运行命令 `.\Scripts\pip.exe install -r <ida_copilot文件夹下的requirements.txt>`
4. 运行命令 `../ida.exe` 打开ida pro

**Comment by wu-yafeng** [comment]
另外一个办法是：
 1. 在IDA Pro目录运行 powershell
 2. 运行命令 `idapyswitch.exe --force-path <ida_pro目录>/python311/python3.dll`
